[package]
name = "restate-opendal-bin"
edition = { workspace = true }
version = { workspace = true }
description = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[[bin]]
name = "restate-opendal"
path = "src/main.rs"

[dependencies]
restate-opendal = { workspace = true }

figment = { version = "0.10.19", features = ["env"] }
humantime-serde = { workspace = true }
opendal = { workspace = true, features = [
  "services-http",
  "services-s3",
  "services-azblob",
  "services-gcs",
  "services-memory",
] }
restate-sdk = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { workspace = true }
